### ISSUE TITLE
Please add a screen shot

### ISSUE THREAD

**Issue by unixorn** [mjrafferty/apollo-zsh-theme#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add themes with screen shots so that users can see what they look like without having to install them.

**Comment by mjrafferty** [comment]
Sorry for the lack of response, I wasn't aware anyone had opened an issue. I've published a complete README including an animated gif showing some of the prompt features.

**Comment by unixorn** [comment]
Thanks for updating, added apollo to the list
