### ISSUE TITLE
readme table of contents has dead links

### ISSUE THREAD

**Issue by spott** [mjrafferty/apollo-zsh-theme#2]
The prezto and oh-my-zsh links for install don't point anywhere.

I'm interested in installing this and I'm using prezto, so it would be nice to get that documentation.

**Comment by mjrafferty** [comment]
I removed those sections from the readme but forgot to remove the links to them. I haven't had a chance to work out installation on those frameworks yet, but once I do I'll add them back in to the readme and update this issue.

**Comment by spott** [comment]
Thanks!

Looking forward to it.

**Comment by mjrafferty** [comment]
I've added instructions for prezto to the readme. Oh-my-zsh will be added in the near future.

**Comment by mjrafferty** [comment]
I went ahead and added the oh-my-zsh instructions now as well. Let me know if you have any issues installing.
