### ISSUE TITLE
Mention APOLLO_THEME in README

### ISSUE THREAD

**Issue by rcarriga** [mjrafferty/apollo-zsh-theme#4]
I don't know if I'm missing something but I can't see any mention of actually setting the theme to a different one using `APOLLO_THEME` anywhere. I only figured it out after watching the video.

It would be great if you mentioned at the start of the configuration section since it is necessary for everything beyond that point.

**Comment by mjrafferty** [comment]
That's a pretty big oversight on my part. Thanks for pointing that out. I'm adding a "Basic Usage" section to the readme now.
